# Generated by Django 4.1.4 on 2023-01-04 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('NOT', 'NotStarted'), ('ON', 'OnGoing'), ('DONE', 'Completed')], default='NOT', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 19, 53, 18, 153366, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 19, 53, 18, 152917, tzinfo=datetime.timezone.utc)),
        ),
    ]
