# Generated by Django 4.1.4 on 2023-01-04 19:55

import datetime
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todo_list', '0004_alter_todo_status_alter_todo_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='user', name='django_user'),

        migrations.AddField(model_name='user', name='date_joined', field=models.DateTimeField(default=timezone.now)),
        migrations.AddField(model_name='user', name='email', field=models.EmailField(default=None, max_length=254, unique=True), preserve_default=False),
        migrations.AddField(model_name='user', name='groups', field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
        migrations.AddField(model_name='user', name='is_active', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='user', name='is_staff', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='user', name='is_superuser', field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
        migrations.AddField(model_name='user', name='last_login', field=models.DateTimeField(blank=True, null=True, verbose_name='last login')),
        migrations.AddField(model_name='user', name='password', field=models.CharField(default=None, max_length=128, verbose_name='password'), preserve_default=False),
        migrations.AddField(model_name='user', name='user_permissions', field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
        migrations.AlterField(model_name='todo', name='updated', field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 21, 7, 18, 792975, tzinfo=datetime.timezone.utc))),
        migrations.AlterField(model_name='user', name='created', field=models.DateTimeField(default=timezone.now)),
        migrations.AlterField(model_name='user', name='updated', field=models.DateTimeField(default=timezone.now)),
    ]